### ISSUE TITLE
Scaling/frequency per axis

### ISSUE THREAD

**Issue by virtualritz** [jackmott/rust-simd-noise#13]
Am I missing something or is it not possible to get the noise(s) scaled non-uniformly?
The `with_freq()` function seems to take only one parameter.

Could `with_freq_2d()`, `with_freq_3d()` etc. be added or the number of parameters of the function just match the number of dimensions of the underlying noise builder?

**Comment by jackmott** [comment]
You could do it by scaling the X and Y inputs values yourself, that is all frequency does.

**Comment by virtualritz** [comment]
I understand this. But what if I want a slice/area of scaled noise from a builder?

**Comment by virtualritz** [comment]
I would look into adding this as it doesn't seem to be that involved. But I never did any SIMD CPU stuff.

```rs
macro_rules! get_3d_noise_helper {
    ...
    let freq_x = S::set1_ps($Setting.freq_x);
    let freq_y = S::set1_ps($Setting.freq_y);
    let freq_z = S::set1_ps($Setting.freq_z);
    ...
    let f = $f(S::mul_ps(x,freq_x),S::mul_ps(y,freq_y),S::mul_ps(z,freq_z) $(,$arg)*);
```

Can you confirm this will work?
Then you would get a PR in a bit. :)

**Comment by jackmott** [comment]
yeah that looks correct.

**Comment by virtualritz** [comment]
How would you like the frequencies per axis to look like in the struct?
```rust
freq: (f32, f32, f32),
```

```rust
freq: [f32; 3],
```

```rust
freq_x: f32,
freq_y: f32,
freq_z: f32,
```

**Comment by jackmott** [comment]
I think the third, that would facilitate changing just one, when using the builder, more easily I think.
What do you think?
And we would want to be sure to apply this to 2d and 4d as well.

**Comment by virtualritz** [comment]
Okidoki. So for the builder we'd keep `with_freq` (seta all axes) and add `with_freq_2d()`, `with_freq_3d()` & `with_freq_4d()` for the resp. multi-dimensional noise versions?

**Comment by jackmott** [comment]
Yeah I think that would be good. That way we don't break the api for anyone too.

**Comment by virtualritz** [comment]
Created PR. [This](https://github.com/jackmott/rust-simd-noise/pull/17/commits/8e72c71e0ad569a664c1d4ebd46b85869116130d) is the commit in question.
Sorry about the extra lines – my editor trims trailing spaces and calls rust-fmt on save. :-]

**Comment by virtualritz** [comment]
I added per-axis freq. support to the `_f64` variants too.

But since my last pull request is still dangling I didn't create a new one. The version with frequency support is in the [`master` branch of my clone](https://github.com/virtualritz/rust-simd-noise/tree/master).

**Comment by jackmott** [comment]
thank, you. the _f64 stuff is still a work in progress, appreciate helping with that too.

**Comment by jackmott** [comment]
once I get the f_64 stuff done I'll do an official release with the new scaling stuff in it
