### ISSUE TITLE
Issues when generating noise in multiple blocks

### ISSUE THREAD

**Issue by caelunshun** [jackmott/rust-simd-noise#9]
Thanks for maintaining this library!

I've been working on a voxel terrain generator where 16x256x16 chunks of voxels are generated using noise. Each chunk is individually generated using `NoiseBuilder::fbm_2d_offset`.

I've observed, however, that there are lines between chunks, and each chunk appears to be separate. A minimal reproducer is as follows:
```rust
use image::{ImageBuffer, Rgb};
use simdnoise::NoiseBuilder;

fn main() {
    let image_length = 256;
    let mut image = ImageBuffer::new(image_length, image_length);

    for chunk_x in 0..16 {
        for chunk_y in 0..16 {
            let noise = NoiseBuilder::fbm_2d_offset(
                (chunk_x * 16) as f32,
                16,
                (chunk_y * 16) as f32,
                16,
            )
            .generate_scaled(0.0, 256.0);

            for x in 0..16 {
                for y in 0..16 {
                    let value = noise[(x << 4) | y] as u8;
                    let pixel = Rgb([value, value, value]);
                    image.put_pixel(chunk_x * 16 + x as u32, chunk_y * 16 + y as u32, pixel);
                }
            }
        }
    }

    image.save("output.png").unwrap();
}
```

`output.png`:
![output](https://i.imgur.com/p1OAjCb.png)

The same happens when using other noise types.

I'm not sure if I'm doing something wrong or if it's an issue with this library, but I suspect it might be the latter.

**Comment by caelunshun** [comment]
When switching `x` and `y` in the index into `noise`, this is the result:

![output](https://i.imgur.com/6AazYlS.png)

Better, but still has problems. Is there something I'm missing?

**Comment by jackmott** [comment]
I'll take a look soon and let you know what I find out.

**Comment by jackmott** [comment]
So I have a sample project that successfully tiles noise here. This uses the minifb crate if you want to run it.:
https://gist.github.com/jackmott/2fb5074ed183a025fe8f641548cd2f9e

I think you are just off on indexing into the noise correctly, it is tricky it took me a while to get it straight too.

However, I did find that in the case of fbm, turbulence, and ridge noise, there is a little bit of a seam on each tile, which should not be there!  So, this did lead to finding a bug, so I'll keep this open and dig deeper. Screenshot of the discontinuity I found below:

![Screenshot from 2019-09-08 20-53-38](https://user-images.githubusercontent.com/4701158/64498585-c2598300-d27a-11e9-8c05-c534ae8d0534.png)

**Comment by jackmott** [comment]
I figured it out!  Using `generate_scaled(min,max)`   causes each thumbnail to get scaled slightly differently, depending on the min and max values that happen to be present in that chunk.  So what you will want to do is use generate, which returns the min and max values.  Keep track of the min and max values across all your chunks, and do the scaling yourself. This means you have to do one more pass through the array, but generate_scaled is doing that too anyway.  And you can usually do this in the same pass you use to draw the pixels into your graphics buffer.

Let me know if you have questions, I'll keep this open till you report that things are working.

**Comment by caelunshun** [comment]
Thanks for the help!

So is there a specific range of values that `generate` returns? I can't keep track of the min and max values across all chunks because this is an infinite world, and each chunk has to be generated independently of all others.

**Comment by jackmott** [comment]
The range of values returned depends on what settings you give to the noise.  octaves, lacunarity etc.

So what you could do is just use the min and max from the first few chunks on all subsequent chunks. Or, via experiment, hard code the adjustment factor you need for the settings you use in your game/different areas of your game.

This is a general issue people have to deal with when using noise functions, its not specific to my library.

**Comment by caelunshun** [comment]
Ah, okay, thanks. I guess this is resolved then!

**Comment by jackmott** [comment]
great let me know if you need any help.

**Comment by Dummyc0m** [comment]
Just encountered the same issue. Thanks for the help!

The output of these noise functions appears to be height major, which seems a little unconventional (since usually it's row-major). It would be nice to document that, if possible.

**Comment by griffi-gh** [comment]
encountered the same issue, still trying to fix it, I guess i'll try  generate without scale...
